import { Function } from "../function.js";
import { Parameter } from "../parameter.js";

export class LookUpTimeFunction extends Function {
  constructor({ defaultCityName }) {
    super({
      name: "lookupTime",
      description:
        "Get the current local time according to the given region and city.",
      parameters: [
        new Parameter({
          name: "city name",
          type: "string",
          description:
            "The city name for which the current time is to be retrieved.",
        }),
      ],
    });
    this.defaultCityName = defaultCityName;
  }

  defaultCityName = "Tokyo";

  async call({ parameters }) {
    if (parameters["city name"] == null || parameters["city name"] == "") {
      parameters["city name"] = this.defaultCityName;
    }

    console.log(
      `${parameters["city name"]}: ${
        LookUpTimeFunction.cityNames[parameters["city name"]]
      }`
    );
    try {
      const response = await fetch(
        `https://worldtimeapi.org/api/timezone/${
          LookUpTimeFunction.cityNames[parameters["city name"]]
        }`
      );
      const data = await response.json();
      const retValue = {
        "city name": parameters["city name"],
        date: data.datetime.split("T")[0],
        time: data.datetime.split("T").pop().split(".")[0],
      };
      return retValue;
    } catch (error) {
      console.error("Error fetching time:", error);
    }
  }

  static cityNames = {
    Abidjan: "Africa/Abidjan",
    アビジャン: "Africa/Abidjan",
    Algiers: "Africa/Algiers",
    アルジェ: "Africa/Algiers",
    Bissau: "Africa/Bissau",
    ビサウ: "Africa/Bissau",
    Cairo: "Africa/Cairo",
    カイロ: "Africa/Cairo",
    Casablanca: "Africa/Casablanca",
    カサブランカ: "Africa/Casablanca",
    Ceuta: "Africa/Ceuta",
    セウタ: "Africa/Ceuta",
    Laayoune: "Africa/El_Aaiun",
    El_Aaiun: "Africa/El_Aaiun",
    "El Aaiun": "Africa/El_Aaiun",
    "El Aaiún": "Africa/El_Aaiun",
    エルアユン: "Africa/El_Aaiun",
    Johannesburg: "Africa/Johannesburg",
    Jozi: "Africa/Johannesburg",
    Joburg: "Africa/Johannesburg",
    "Jo'burg": "Africa/Johannesburg",
    ヨハネスブルグ: "Africa/Johannesburg",
    ヨハネスバーグ: "Africa/Johannesburg",
    Juba: "Africa/Juba",
    ジュバ: "Africa/Juba",
    Khartoum: "Africa/Khartoum",
    Khartum: "Africa/Khartoum",
    カルトゥーム: "Africa/Khartoum",
    ハルツーム: "Africa/Khartoum",
    ハルトゥーム: "Africa/Khartoum",
    Lagos: "Africa/Lagos",
    ラゴス: "Africa/Lagos",
    Maputo: "Africa/Maputo",
    マプト: "Africa/Maputo",
    Monrovia: "Africa/Monrovia",
    モンロビア: "Africa/Monrovia",
    Nairobi: "Africa/Nairobi",
    ナイロビ: "Africa/Nairobi",
    Ndjamena: "Africa/Ndjamena",
    "N'Djamena": "Africa/Ndjamena",
    エンジャメナ: "Africa/Ndjamena",
    ンジャメナ: "Africa/Ndjamena",
    ヌジャメナ: "Africa/Ndjamena",
    ウンジャメナ: "Africa/Ndjamena",
    Sao_Tome: "Africa/Sao_Tome",
    "Sao Tome": "Africa/Sao_Tome",
    "São Tomé": "Africa/Sao_Tome",
    サントメ: "Africa/Sao_Tome",
    Tripoli: "Africa/Tripoli",
    トリポリ: "Africa/Tripoli",
    Tunis: "Africa/Tunis",
    チュニス: "Africa/Tunis",
    Windhoek: "Africa/Windhoek",
    ウィントフック: "Africa/Windhoek",
    Adak: "America/Adak",
    アダック: "America/Adak",
    Anchorage: "America/Anchorage",
    アンカレッジ: "America/Anchorage",
    アンカレジ: "America/Anchorage",
    Araguaina: "America/Araguaina",
    アラグアイナ: "America/Araguaina",
    Buenos_Aires: "America/Argentina/Buenos_Aires",
    "Buenos Aires": "America/Argentina/Buenos_Aires",
    ブエノスアイレス: "America/Argentina/Buenos_Aires",
    Catamarca: "America/Argentina/Catamarca",
    カタマルカ: "America/Argentina/Catamarca",
    Cordoba: "America/Argentina/Cordoba",
    Córdoba: "America/Argentina/Cordoba",
    コルドバ: "America/Argentina/Cordoba",
    Jujuy: "America/Argentina/Jujuy",
    フフイ: "America/Argentina/Jujuy",
    La_Rioja: "America/Argentina/La_Rioja",
    "La Rioja": "America/Argentina/La_Rioja",
    ラリオハ: "America/Argentina/La_Rioja",
    "ラ・リオハ": "America/Argentina/La_Rioja",
    Mendoza: "America/Argentina/Mendoza",
    メンドーサ: "America/Argentina/Mendoza",
    メンドサ: "America/Argentina/Mendoza",
    Rio_Gallegos: "America/Argentina/Rio_Gallegos",
    "Río Gallegos": "America/Argentina/Rio_Gallegos",
    "Rio Gallegos": "America/Argentina/Rio_Gallegos",
    リオガジェゴス: "America/Argentina/Rio_Gallegos",
    "リオ・ガジェゴス": "America/Argentina/Rio_Gallegos",
    Salta: "America/Argentina/Salta",
    サルタ: "America/Argentina/Salta",
    San_Juan: "America/Argentina/San_Juan",
    "San Juan": "America/Argentina/San_Juan",
    サンフアン: "America/Argentina/San_Juan",
    "サン・フアン": "America/Argentina/San_Juan",
    San_Luis: "America/Argentina/San_Luis",
    "San Luis": "America/Argentina/San_Luis",
    サンルイス: "America/Argentina/San_Luis",
    "サン・ルイス": "America/Argentina/San_Luis",
    Tucuman: "America/Argentina/Tucuman",
    Tucumán: "America/Argentina/Tucuman",
    トゥクマン: "America/Argentina/Tucuman",
    Ushuaia: "America/Argentina/Ushuaia",
    ウシュアイア: "America/Argentina/Ushuaia",
    ウスワイア: "America/Argentina/Ushuaia",
    ウスワヤ: "America/Argentina/Ushuaia",
    Asuncion: "America/Asuncion",
    Asunción: "America/Asuncion",
    アスンシオン: "America/Asuncion",
    Bahia: "America/Bahia",
    バイーア: "America/Bahia",
    Bahia_Banderas: "America/Bahia_Banderas",
    "Bahia Banderas": "America/Bahia_Banderas",
    バイアバンデラス: "America/Bahia_Banderas",
    Barbados: "America/Barbados",
    バルバドス: "America/Barbados",
    Belem: "America/Belem",
    Belém: "America/Belem",
    ベレン: "America/Belem",
    Belize: "America/Belize",
    ベリーズ: "America/Belize",
    Boa_Vista: "America/Boa_Vista",
    "Boa Vista": "America/Boa_Vista",
    ボアビスタ: "America/Boa_Vista",
    Bogota: "America/Bogota",
    Bogotá: "America/Bogota",
    ボゴタ: "America/Bogota",
    Boise: "America/Boise",
    ボイシ: "America/Boise",
    ボイジー: "America/Boise",
    ボイシー: "America/Boise",
    Cambridge_Bay: "America/Cambridge_Bay",
    "Cambridge Bay": "America/Cambridge_Bay",
    ケンブリッジベイ: "America/Cambridge_Bay",
    "ケンブリッジ・ベイ": "America/Cambridge_Bay",
    Campo_Grande: "America/Campo_Grande",
    "Campo Grande": "America/Campo_Grande",
    カンポグランデ: "America/Campo_Grande",
    "カンポ・グランデ": "America/Campo_Grande",
    Cancun: "America/Cancun",
    カンクン: "America/Cancun",
    Caracas: "America/Caracas",
    カラカス: "America/Caracas",
    Cayenne: "America/Cayenne",
    カイエンヌ: "America/Cayenne",
    Chicago: "America/Chicago",
    シカゴ: "America/Chicago",
    Chihuahua: "America/Chihuahua",
    チワワ: "America/Chihuahua",
    Ciudad_Juarez: "America/Ciudad_Juarez",
    "Ciudad Juarez": "America/Ciudad_Juarez",
    "Ciudad Juárez": "America/Ciudad_Juarez",
    シウダーフアレス: "America/Ciudad_Juarez",
    フアレス: "America/Ciudad_Juarez",
    "シウダー・フアレス": "America/Ciudad_Juarez",
    Costa_Rica: "America/Costa_Rica",
    "Costa Rica": "America/Costa_Rica",
    コスタリカ: "America/Costa_Rica",
    "コスタ・リカ": "America/Costa_Rica",
    Cuiaba: "America/Cuiaba",
    Cuiabá: "America/Cuiaba",
    クイアバ: "America/Cuiaba",
    クイアバー: "America/Cuiaba",
    Danmarkshavn: "America/Danmarkshavn",
    ダンマークシャウン: "America/Danmarkshavn",
    Dawson: "America/Dawson",
    ドーソン: "America/Dawson",
    Dawson_Creek: "America/Dawson_Creek",
    "Dawson Creek": "America/Dawson_Creek",
    ドーソンクリーク: "America/Dawson_Creek",
    "ドーソン・クリーク": "America/Dawson_Creek",
    Denver: "America/Denver",
    デンバー: "America/Denver",
    Detroit: "America/Detroit",
    デトロイト: "America/Detroit",
    Edmonton: "America/Edmonton",
    エドモントン: "America/Edmonton",
    Eirunepe: "America/Eirunepe",
    エイルネペ: "America/Eirunepe",
    El_Salvador: "America/El_Salvador",
    "El Salvador": "America/El_Salvador",
    エルサルバドル: "America/El_Salvador",
    "エル・サルバドル": "America/El_Salvador",
    Fort_Nelson: "America/Fort_Nelson",
    "Fort Nelson": "America/Fort_Nelson",
    フォートネルソン: "America/Fort_Nelson",
    "フォート・ネルソン": "America/Fort_Nelson",
    Fortaleza: "America/Fortaleza",
    フォルタレザ: "America/Fortaleza",
    フォルタレーザ: "America/Fortaleza",
    Glace_Bay: "America/Glace_Bay",
    "Glace Bay": "America/Glace_Bay",
    グレースベイ: "America/Glace_Bay",
    "グレース・ベイ": "America/Glace_Bay",
    Goose_Bay: "America/Goose_Bay",
    "Goose Bay": "America/Goose_Bay",
    グースベイ: "America/Goose_Bay",
    "グース・ベイ": "America/Goose_Bay",
    Grand_Turk: "America/Grand_Turk",
    "Grand Turk": "America/Grand_Turk",
    グランドターク: "America/Grand_Turk",
    "グランド・ターク": "America/Grand_Turk",
    Guatemala: "America/Guatemala",
    グアテマラ: "America/Guatemala",
    Guayaquil: "America/Guayaquil",
    グアヤキル: "America/Guayaquil",
    Guyana: "America/Guyana",
    ガイアナ: "America/Guyana",
    Halifax: "America/Halifax",
    ハリファックス: "America/Halifax",
    Havana: "America/Havana",
    ハバナ: "America/Havana",
    Hermosillo: "America/Hermosillo",
    エルモシージョ: "America/Hermosillo",
    Indianapolis: "America/Indiana/Indianapolis",
    インディアナポリス: "America/Indiana/Indianapolis",
    Knox: "America/Indiana/Knox",
    ノックス: "America/Indiana/Knox",
    Marengo: "America/Indiana/Marengo",
    マレンゴ: "America/Indiana/Marengo",
    Petersburg: "America/Indiana/Petersburg",
    ピーターズバーグ: "America/Indiana/Petersburg",
    Tell_City: "America/Indiana/Tell_City",
    "Tell City": "America/Indiana/Tell_City",
    テルシティ: "America/Indiana/Tell_City",
    "テル・シティ": "America/Indiana/Tell_City",
    Vevay: "America/Indiana/Vevay",
    ベベイ: "America/Indiana/Vevay",
    Vincennes: "America/Indiana/Vincennes",
    ヴィンセンス: "America/Indiana/Vincennes",
    Winamac: "America/Indiana/Winamac",
    ウィナマック: "America/Indiana/Winamac",
    Inuvik: "America/Inuvik",
    イヌヴィック: "America/Inuvik",
    Iqaluit: "America/Iqaluit",
    イカルイト: "America/Iqaluit",
    Jamaica: "America/Jamaica",
    ジャマイカ: "America/Jamaica",
    Juneau: "America/Juneau",
    ジュノー: "America/Juneau",
    Louisville: "America/Kentucky/Louisville",
    ルイビル: "America/Kentucky/Louisville",
    Monticello: "America/Kentucky/Monticello",
    モンティチェロ: "America/Kentucky/Monticello",
    La_Paz: "America/La_Paz",
    ラパス: "America/La_Paz",
    Lima: "America/Lima",
    リマ: "America/Lima",
    Los_Angeles: "America/Los_Angeles",
    "Los Angeles": "America/Los_Angeles",
    LA: "America/Los_Angeles",
    ロサンゼルス: "America/Los_Angeles",
    ロス: "America/Los_Angeles",
    Maceio: "America/Maceio",
    Maceió: "America/Maceio",
    マセイオ: "America/Maceio",
    Managua: "America/Managua",
    マナグア: "America/Managua",
    Manaus: "America/Manaus",
    マナウス: "America/Manaus",
    Martinique: "America/Martinique",
    マルティニーク: "America/Martinique",
    Matamoros: "America/Matamoros",
    マタモロス: "America/Matamoros",
    Mazatlan: "America/Mazatlan",
    マサトラン: "America/Mazatlan",
    Menominee: "America/Menominee",
    メノミニー: "America/Menominee",
    Merida: "America/Merida",
    メリダ: "America/Merida",
    Metlakatla: "America/Metlakatla",
    メトラカトラ: "America/Metlakatla",
    Mexico_City: "America/Mexico_City",
    "Mexico City": "America/Mexico_City",
    メキシコシティ: "America/Mexico_City",
    Miquelon: "America/Miquelon",
    ミクロン: "America/Miquelon",
    Moncton: "America/Moncton",
    モンクトン: "America/Moncton",
    Monterrey: "America/Monterrey",
    モンテレイ: "America/Monterrey",
    Montevideo: "America/Montevideo",
    モンテビデオ: "America/Montevideo",
    New_York: "America/New_York",
    "New York": "America/New_York",
    ニューヨーク: "America/New_York",
    Nome: "America/Nome",
    ノーム: "America/Nome",
    Noronha: "America/Noronha",
    ノロニャ: "America/Noronha",
    Beulah: "America/North_Dakota/Beulah",
    ビューラ: "America/North_Dakota/Beulah",
    Center: "America/North_Dakota/Center",
    センター: "America/North_Dakota/Center",
    North_Dakota: "America/North_Dakota/Center",
    "North Dakota": "America/North_Dakota/Center",
    ノースダコタ: "America/North_Dakota/Center",
    "ノース・ダコタ": "America/North_Dakota/Center",
    New_Salem: "America/North_Dakota/New_Salem",
    "New Salem": "America/North_Dakota/New_Salem",
    ニューセーラム: "America/North_Dakota/New_Salem",
    "ニュー・セーラム": "America/North_Dakota/New_Salem",
    Nuuk: "America/Nuuk",
    ヌーク: "America/Nuuk",
    Ojinaga: "America/Ojinaga",
    オヒナガ: "America/Ojinaga",
    Panama: "America/Panama",
    パナマ: "America/Panama",
    Paramaribo: "America/Paramaribo",
    パラマリボ: "America/Paramaribo",
    Phoenix: "America/Phoenix",
    フェニックス: "America/Phoenix",
    "Port-au-Prince": "America/Port-au-Prince",
    "Port au Prince": "America/Port-au-Prince",
    ポルトープランス: "America/Port-au-Prince",
    "ポルト・プランス": "America/Port-au-Prince",
    Porto_Velho: "America/Porto_Velho",
    "Porto Velho": "America/Porto_Velho",
    ポルトベーリョ: "America/Porto_Velho",
    "ポルト・ベーリョ": "America/Porto_Velho",
    Puerto_Rico: "America/Puerto_Rico",
    "Puerto Rico": "America/Puerto_Rico",
    プエルトリコ: "America/Puerto_Rico",
    "プエルト・リコ": "America/Puerto_Rico",
    Punta_Arenas: "America/Punta_Arenas",
    "Punta Arenas": "America/Punta_Arenas",
    プンタアレナス: "America/Punta_Arenas",
    Rankin_Inlet: "America/Rankin_Inlet",
    "Rankin Inlet": "America/Rankin_Inlet",
    ランキンインレット: "America/Rankin_Inlet",
    "ランキン・インレット": "America/Rankin_Inlet",
    Recife: "America/Recife",
    レシフェ: "America/Recife",
    Regina: "America/Regina",
    レジーナ: "America/Regina",
    Resolute: "America/Resolute",
    レゾリュート: "America/Resolute",
    Rio_Branco: "America/Rio_Branco",
    "Rio Branco": "America/Rio_Branco",
    リオブランコ: "America/Rio_Branco",
    "リオ・ブランコ": "America/Rio_Branco",
    Santarem: "America/Santarem",
    サンタレム: "America/Santarem",
    Santiago: "America/Santiago",
    サンティアゴ: "America/Santiago",
    サンチアゴ: "America/Santiago",
    Santo_Domingo: "America/Santo_Domingo",
    "Santo Domingo": "America/Santo_Domingo",
    サントドミンゴ: "America/Santo_Domingo",
    Sao_Paulo: "America/Sao_Paulo",
    "São Paulo": "America/Sao_Paulo",
    サンパウロ: "America/Sao_Paulo",
    Scoresbysund: "America/Scoresbysund",
    スコレスビサンド: "America/Scoresbysund",
    Sitka: "America/Sitka",
    シトカ: "America/Sitka",
    St_Johns: "America/St_Johns",
    "St Johns": "America/St_Johns",
    セントジョンズ: "America/St_Johns",
    "セント・ジョンズ": "America/St_Johns",
    Swift_Current: "America/Swift_Current",
    "Swift Current": "America/Swift_Current",
    スウィフトカレント: "America/Swift_Current",
    Tegucigalpa: "America/Tegucigalpa",
    テグシガルパ: "America/Tegucigalpa",
    Thule: "America/Thule",
    スーレ: "America/Thule",
    Tijuana: "America/Tijuana",
    ティフアナ: "America/Tijuana",
    Toronto: "America/Toronto",
    トロント: "America/Toronto",
    Vancouver: "America/Vancouver",
    バンクーバー: "America/Vancouver",
    Whitehorse: "America/Whitehorse",
    ホワイトホース: "America/Whitehorse",
    Winnipeg: "America/Winnipeg",
    ウィニペグ: "America/Winnipeg",
    Yakutat: "America/Yakutat",
    ヤクタット: "America/Yakutat",
    ヤクタト: "America/Yakutat",
    Casey: "Antarctica/Casey",
    ケーシー: "Antarctica/Casey",
    Davis: "Antarctica/Davis",
    デービス: "Antarctica/Davis",
    Macquarie: "Antarctica/Macquarie",
    マッコリー: "Antarctica/Macquarie",
    Mawson: "Antarctica/Mawson",
    モーソン: "Antarctica/Mawson",
    Palmer: "Antarctica/Palmer",
    パーマー: "Antarctica/Palmer",
    Rothera: "Antarctica/Rothera",
    ロゼラ: "Antarctica/Rothera",
    Troll: "Antarctica/Troll",
    トロール: "Antarctica/Troll",
    Almaty: "Asia/Almaty",
    アルマトイ: "Asia/Almaty",
    Amman: "Asia/Amman",
    アンマン: "Asia/Amman",
    Anadyr: "Asia/Anadyr",
    アナディリ: "Asia/Anadyr",
    Aqtau: "Asia/Aqtau",
    アクタウ: "Asia/Aqtau",
    Ashgabat: "Asia/Ashgabat",
    アシガバート: "Asia/Ashgabat",
    Atyrau: "Asia/Atyrau",
    アティラウ: "Asia/Atyrau",
    Baghdad: "Asia/Baghdad",
    バグダッド: "Asia/Baghdad",
    Baku: "Asia/Baku",
    バクー: "Asia/Baku",
    Bangkok: "Asia/Bangkok",
    バンコク: "Asia/Bangkok",
    Barnaul: "Asia/Barnaul",
    バルナウル: "Asia/Barnaul",
    Beirut: "Asia/Beirut",
    ベイルート: "Asia/Beirut",
    Bishkek: "Asia/Bishkek",
    ビシュケク: "Asia/Bishkek",
    Chita: "Asia/Chita",
    チタ: "Asia/Chita",
    Choibalsan: "Asia/Choibalsan",
    チョイバルサン: "Asia/Choibalsan",
    Colombo: "Asia/Colombo",
    コロンボ: "Asia/Colombo",
    Damascus: "Asia/Damascus",
    ダマスカス: "Asia/Damascus",
    Dhaka: "Asia/Dhaka",
    ダッカ: "Asia/Dhaka",
    Dili: "Asia/Dili",
    ディリ: "Asia/Dili",
    Dubai: "Asia/Dubai",
    ドバイ: "Asia/Dubai",
    Dushanbe: "Asia/Dushanbe",
    ドゥシャンベ: "Asia/Dushanbe",
    Famagusta: "Asia/Famagusta",
    ファマグスタ: "Asia/Famagusta",
    Gaza: "Gaza",
    ガザ: "Gaza",
    Hebron: "Asia/Hebron",
    ヘブロン: "Asia/Hebron",
    Ho_Chi_Minh: "Asia/Ho_Chi_Minh",
    "Ho Chi Minh": "Asia/Ho_Chi_Minh",
    ホーチミン: "Asia/Ho_Chi_Minh",
    Hong_Kong: "Asia/Hong_Kong",
    "Hong Kong": "Asia/Hong_Kong",
    香港: "Asia/Hong_Kong",
    Hovd: "Asia/Hovd",
    ホブド: "Asia/Hovd",
    Irkutsk: "Asia/Irkutsk",
    イルクーツク: "Asia/Irkutsk",
    Jakarta: "Asia/Jakarta",
    ジャカルタ: "Asia/Jakarta",
    Jayapura: "Asia/Jayapura",
    ジャヤプラ: "Asia/Jayapura",
    Jerusalem: "Asia/Jerusalem",
    エルサレム: "Asia/Jerusalem",
    Kabul: "Asia/Kabul",
    カブール: "Asia/Kabul",
    Kamchatka: "Asia/Kamchatka",
    カムチャツカ: "Asia/Kamchatka",
    Karachi: "Asia/Karachi",
    カラチ: "Asia/Karachi",
    Kathmandu: "Asia/Kathmandu",
    カトマンズ: "Asia/Kathmandu",
    Khandyga: "Asia/Khandyga",
    ハンディガ: "Asia/Khandyga",
    Kolkata: "Asia/Kolkata",
    コルカタ: "Asia/Kolkata",
    カルカッタ: "Asia/Kolkata",
    Krasnoyarsk: "Asia/Krasnoyarsk",
    クラスノヤルスク: "Asia/Krasnoyarsk",
    Kuching: "Asia/Kuching",
    クチン: "Asia/Kuching",
    Macau: "Asia/Macau",
    マカオ: "Asia/Macau",
    Magadan: "Asia/Magadan",
    マガダン: "Asia/Magadan",
    Makassar: "Asia/Makassar",
    マカッサル: "Asia/Makassar",
    Manila: "Asia/Manila",
    マニラ: "Asia/Manila",
    Nicosia: "Asia/Nicosia",
    ニコシア: "Asia/Nicosia",
    Novokuznetsk: "Asia/Novokuznetsk",
    ノヴォクズネツク: "Asia/Novokuznetsk",
    Omsk: "Asia/Omsk",
    オムスク: "Asia/Omsk",
    Oral: "Asia/Oral",
    オラル: "Asia/Oral",
    Pontianak: "Asia/Pontianak",
    ポンティアナック: "Asia/Pontianak",
    Pyongyang: "Asia/Pyongyang",
    ピョンヤン: "Asia/Pyongyang",
    平壌: "Asia/Pyongyang",
    Qatar: "Asia/Qatar",
    カタール: "Asia/Qatar",
    Qostanay: "Asia/Qostanay",
    コスタナイ: "Asia/Qostanay",
    Qyzylorda: "Asia/Qyzylorda",
    クズロルダ: "Asia/Qyzylorda",
    Riyadh: "Asia/Riyadh",
    リヤド: "Asia/Riyadh",
    Sakhalin: "Asia/Sakhalin",
    サハリン: "Asia/Sakhalin",
    Samarkand: "Asia/Samarkand",
    サマルカンド: "Asia/Samarkand",
    Seoul: "Asia/Seoul",
    ソウル: "Asia/Seoul",
    Shanghai: "Asia/Shanghai",
    上海: "Asia/Shanghai",
    シャンハイ: "Asia/Shanghai",
    Singapore: "Asia/Singapore",
    シンガポール: "Asia/Singapore",
    Srednekolymsk: "Asia/Srednekolymsk",
    スレドネコリムスク: "Asia/Srednekolymsk",
    Taipei: "Asia/Taipei",
    台北: "Asia/Taipei",
    タイペイ: "Asia/Taipei",
    Tashkent: "Asia/Tashkent",
    タシケント: "Asia/Tashkent",
    Tbilisi: "Asia/Tbilisi",
    トビリシ: "Asia/Tbilisi",
    Tehran: "Asia/Tehran",
    テヘラン: "Asia/Tehran",
    Thimphu: "Asia/Thimphu",
    ティンプー: "Asia/Thimphu",
    Tokyo: "Asia/Tokyo",
    東京: "Asia/Tokyo",
    Japan: "Asia/Tokyo",
    Yokohama: "Asia/Tokyo",
    横浜: "Asia/Tokyo",
    日本: "Asia/Tokyo",
    Kyoto: "Asia/Tokyo",
    京都: "Asia/Tokyo",
    Osaka: "Asia/Tokyo",
    大阪: "Asia/Tokyo",
    Nagoya: "Asia/Tokyo",
    名古屋: "Asia/Tokyo",
    Sapporo: "Asia/Tokyo",
    札幌: "Asia/Tokyo",
    Fukuoka: "Asia/Tokyo",
    福岡: "Asia/Tokyo",
    Tomsk: "Asia/Tomsk",
    トムスク: "Asia/Tomsk",
    Ulaanbaatar: "Asia/Ulaanbaatar",
    ウランバートル: "Asia/Ulaanbaatar",
    Urumqi: "Asia/Urumqi",
    ウルムチ: "Asia/Urumqi",
    "Ust-Nera": "Asia/Ust-Nera",
    ウストネラ: "Asia/Ust-Nera",
    Vladivostok: "Asia/Vladivostok",
    ウラジオストク: "Asia/Vladivostok",
    Yakutsk: "Asia/Yakutsk",
    ヤクーツク: "Asia/Yakutsk",
    Yangon: "Asia/Yangon",
    ヤンゴン: "Asia/Yangon",
    Yekaterinburg: "Asia/Yekaterinburg",
    エカテリンブルク: "Asia/Yekaterinburg",
    Yerevan: "Asia/Yerevan",
    エレバン: "Asia/Yerevan",
    Azores: "Atlantic/Azores",
    アゾレス: "Atlantic/Azores",
    Bermuda: "Atlantic/Bermuda",
    バミューダ: "Atlantic/Bermuda",
    Canary: "Atlantic/Canary",
    カナリア: "Atlantic/Canary",
    Cape_Verde: "Atlantic/Cape_Verde",
    "Cape Verde": "Atlantic/Cape_Verde",
    カーボベルデ: "Atlantic/Cape_Verde",
    "カーボ・ベルデ": "Atlantic/Cape_Verde",
    Faroe: "Atlantic/Faroe",
    フェロー: "Atlantic/Faroe",
    Madeira: "Atlantic/Madeira",
    マデイラ: "Atlantic/Madeira",
    South_Georgia: "Atlantic/South_Georgia",
    "South Georgia": "Atlantic/South_Georgia",
    サウスジョージア: "Atlantic/South_Georgia",
    "サウス・ジョージア": "Atlantic/South_Georgia",
    Stanley: "Atlantic/Stanley",
    スタンレー: "Atlantic/Stanley",
    Adelaide: "Australia/Adelaide",
    アデレード: "Australia/Adelaide",
    Brisbane: "Australia/Brisbane",
    ブリスベン: "Australia/Brisbane",
    Broken_Hill: "Australia/Broken_Hill",
    "Broken Hill": "Australia/Broken_Hill",
    ブロークンヒル: "Australia/Broken_Hill",
    Darwin: "Australia/Darwin",
    ダーウィン: "Australia/Darwin",
    Eucla: "Australia/Eucla",
    エウクラ: "Australia/Eucla",
    Hobart: "Australia/Hobart",
    ホバート: "Australia/Hobart",
    Lindeman: "Australia/Lindeman",
    リンデマン: "Australia/Lindeman",
    Lord_Howe: "Australia/Lord_Howe",
    "Lord Howe": "Australia/Lord_Howe",
    ロードハウ: "Australia/Lord_Howe",
    Melbourne: "Australia/Melbourne",
    メルボルン: "Australia/Melbourne",
    Perth: "Australia/Perth",
    パース: "Australia/Perth",
    Sydney: "Australia/Sydney",
    シドニー: "Australia/Sydney",
    Andorra: "Europe/Andorra",
    アンドラ: "Europe/Andorra",
    Astrakhan: "Europe/Astrakhan",
    アストラハン: "Europe/Astrakhan",
    Athens: "Europe/Athens",
    アテネ: "Europe/Athens",
    Belgrade: "Europe/Belgrade",
    ベオグラード: "Europe/Belgrade",
    Berlin: "Europe/Berlin",
    ベルリン: "Europe/Berlin",
    Brussels: "Europe/Brussels",
    ブリュッセル: "Europe/Brussels",
    Bucharest: "Europe/Bucharest",
    ブカレスト: "Europe/Bucharest",
    Budapest: "Europe/Budapest",
    ブダペスト: "Europe/Budapest",
    Chisinau: "Europe/Chisinau",
    Chişinău: "Europe/Chisinau",
    キシナウ: "Europe/Chisinau",
    Dublin: "Europe/Dublin",
    ダブリン: "Europe/Dublin",
    Gibraltar: "Europe/Gibraltar",
    ジブラルタル: "Europe/Gibraltar",
    Helsinki: "Europe/Helsinki",
    ヘルシンキ: "Europe/Helsinki",
    Istanbul: "Europe/Istanbul",
    イスタンブール: "Europe/Istanbul",
    Kaliningrad: "Europe/Kaliningrad",
    カリーニングラード: "Europe/Kaliningrad",
    Kirov: "Europe/Kirov",
    キーロフ: "Europe/Kirov",
    Kyiv: "Europe/Kiev",
    Kiev: "Europe/Kiev",
    キエフ: "Europe/Kiev",
    キーウ: "Europe/Kiev",
    Lisbon: "Europe/Lisbon",
    リスボン: "Europe/Lisbon",
    London: "Europe/London",
    ロンドン: "Europe/London",
    Madrid: "Europe/Madrid",
    マドリード: "Europe/Madrid",
    マドリッド: "Europe/Madrid",
    Malta: "Europe/Malta",
    マルタ: "Europe/Malta",
    Minsk: "Europe/Minsk",
    ミンスク: "Europe/Minsk",
    Moscow: "Europe/Moscow",
    モスクワ: "Europe/Moscow",
    Paris: "Europe/Paris",
    パリ: "Europe/Paris",
    Prague: "Europe/Prague",
    プラハ: "Europe/Prague",
    Riga: "Europe/Riga",
    リガ: "Europe/Riga",
    Rome: "Europe/Rome",
    ローマ: "Europe/Rome",
    Samara: "Europe/Samara",
    サマラ: "Europe/Samara",
    Saratov: "Europe/Saratov",
    サラトフ: "Europe/Saratov",
    Simferopol: "Europe/Simferopol",
    シンフェロポリ: "Europe/Simferopol",
    Sofia: "Europe/Sofia",
    ソフィア: "Europe/Sofia",
    Tallinn: "Europe/Tallinn",
    タリン: "Europe/Tallinn",
    Tirane: "Europe/Tirane",
    Tirana: "Europe/Tirane",
    ティラナ: "Europe/Tirane",
    Ulyanovsk: "Europe/Ulyanovsk",
    ウリヤノフスク: "Europe/Ulyanovsk",
    Vienna: "Europe/Vienna",
    ウィーン: "Europe/Vienna",
    Vilnius: "Europe/Vilnius",
    ビリニュス: "Europe/Vilnius",
    Volgograd: "Europe/Volgograd",
    ヴォルゴグラード: "Europe/Volgograd",
    Warsaw: "Europe/Warsaw",
    ワルシャワ: "Europe/Warsaw",
    Zurich: "Europe/Zurich",
    Zürich: "Europe/Zurich",
    チューリッヒ: "Europe/Zurich",
    チューリヒ: "Europe/Zurich",
    Chagos: "Indian/Chagos",
    チャゴス: "Indian/Chagos",
    Moldves: "Indian/Maldives",
    モルディブ: "Indian/Maldives",
    Mauritius: "Indian/Mauritius",
    モーリシャス: "Indian/Mauritius",
    Apia: "Pacific/Apia",
    アピア: "Pacific/Apia",
    Auckland: "Pacific/Auckland",
    オークランド: "Pacific/Auckland",
    Bougainville: "Pacific/Bougainville",
    ブーゲンビル: "Pacific/Bougainville",
    Chatham: "Pacific/Chatham",
    チャタム: "Pacific/Chatham",
    Easter: "Pacific/Easter",
    イースター: "Pacific/Easter",
    Efate: "Pacific/Efate",
    エファテ: "Pacific/Efate",
    Fakaofo: "Pacific/Fakaofo",
    ファカオフォ: "Pacific/Fakaofo",
    Fiji: "Pacific/Fiji",
    フィジー: "Pacific/Fiji",
    Galapagos: "Pacific/Galapagos",
    ガラパゴス: "Pacific/Galapagos",
    Gambier: "Pacific/Gambier",
    ガンビエ: "Pacific/Gambier",
    Guadalcanal: "Pacific/Guadalcanal",
    グアダルカナル: "Pacific/Guadalcanal",
    ガダルカナル: "Pacific/Guadalcanal",
    Guam: "Pacific/Guam",
    グアム: "Pacific/Guam",
    Honolulu: "Pacific/Honolulu",
    ホノルル: "Pacific/Honolulu",
    Kanton: "Pacific/Kanton",
    カントン: "Pacific/Kanton",
    Kiritimati: "Pacific/Kiritimati",
    キリスマス: "Pacific/Kiritimati",
    Kosrae: "Pacific/Kosrae",
    コスラエ: "Pacific/Kosrae",
    Kwajalein: "Pacific/Kwajalein",
    クェゼリン: "Pacific/Kwajalein",
    Marquesas: "Pacific/Marquesas",
    マルキーズ: "Pacific/Marquesas",
    Nauru: "Pacific/Nauru",
    ナウル: "Pacific/Nauru",
    Niue: "Pacific/Niue",
    ニウエ: "Pacific/Niue",
    Norfolk: "Pacific/Norfolk",
    ノーフォーク: "Pacific/Norfolk",
    Noumea: "Pacific/Noumea",
    ヌメア: "Pacific/Noumea",
    Pago_Pago: "Pacific/Pago_Pago",
    "Pago Pago": "Pacific/Pago_Pago",
    パゴパゴ: "Pacific/Pago_Pago",
    Palau: "Pacific/Palau",
    パラオ: "Pacific/Palau",
    Pitcairn: "Pacific/Pitcairn",
    ピトケアン: "Pacific/Pitcairn",
    Port_Moresby: "Pacific/Port_Moresby",
    "Port Moresby": "Pacific/Port_Moresby",
    ポートモレスビー: "Pacific/Port_Moresby",
    Rarotonga: "Pacific/Rarotonga",
    ラロトンガ: "Pacific/Rarotonga",
    Tahiiti: "Pacific/Tahiti",
    タヒチ: "Pacific/Tahiti",
    Tarawa: "Pacific/Tarawa",
    タラワ: "Pacific/Tarawa",
    Tongatapu: "Pacific/Tongatapu",
    トンガタプ: "Pacific/Tongatapu",
  };
}
